version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: govconone
      POSTGRES_USER: govconone
      POSTGRES_PASSWORD: govconone123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      PORT: 8000
      DATABASE_URL: postgresql://govconone:govconone123@postgres:5432/govconone
      JWT_SECRET: dev-jwt-secret-key
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000/api

volumes:
  postgres_data:
